# Generated by Django 4.1.6 on 2023-02-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_task_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
