# Generated by Django 4.1.6 on 2023-02-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_task_options_task_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="title", field=models.CharField(max_length=100),
        ),
    ]
