# Generated by Django 4.1.6 on 2023-02-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="title", field=models.CharField(max_length=150),
        ),
    ]
